# Generated by Django 2.1.2 on 2018-11-11 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homephoto1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('homephoto2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('homephoto3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('home2photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('home2photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('home2photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth1photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth1photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth1photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth2photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth2photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth2photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth3photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth3photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth3photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth4photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth4photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth4photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone1photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone1photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone1photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone2photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone2photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone2photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone3photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone3photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone3photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone4photo1', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone4photo2', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone4photo3', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('cloth5photo', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
                ('phone5photo', models.ImageField(blank=True, default=None, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='T-shirt , Pantalon , Sheos , Phone , Laptop...etc', max_length=120)),
                ('color', models.CharField(help_text='red , green , black , blue....', max_length=120)),
                ('size', models.CharField(default='S', help_text='S,M,L,XL,XXL', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('describtion', models.TextField(help_text='this is optional if type is ACCESSORIES', null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.CharField(choices=[('CLOTHES', 'CLOTHES'), ('PHONES', 'PHONES')], default=None, max_length=7)),
                ('shop_name', models.CharField(max_length=25)),
                ('shop_phone', models.CharField(max_length=11)),
                ('shop_location', models.CharField(max_length=220)),
                ('num_of_share', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('shop_image', models.ImageField(default=None, upload_to='static/images')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['num_of_share'],
            },
        ),
        migrations.CreateModel(
            name='TextAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1_text', models.CharField(default=None, help_text='write you advertise here', max_length=300)),
                ('address2_text', models.CharField(default=None, help_text='write you advertise here', max_length=300)),
                ('address3_text', models.CharField(default=None, help_text='write you advertise here', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothesphonesapp.Shop'),
        ),
    ]
